# Generated by Django 5.0.1 on 2024-01-13 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_useradmin_delete_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useradmin',
            name='user_id',
        ),
        migrations.AddField(
            model_name='useradmin',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='useradmin',
            name='name',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useradmin',
            name='phone_no',
            field=models.CharField(default=3232342, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='useradmin',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='useradmin',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
